image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - build
  - publish

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_IMAGE_TAG docker

publish-image:
  stage: publish
  script:
    - docker push $CONTAINER_IMAGE_TAG
  only:
    - master
